/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameSessionIdRouteImport } from './routes/game.$sessionId'
import { Route as ApiLeaveRouteImport } from './routes/api/leave'
import { Route as ApiEventsSessionIdRouteImport } from './routes/api/events/$sessionId'
import { Route as ApiCronCleanupRouteImport } from './routes/api/cron/cleanup'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSessionIdRoute = GameSessionIdRouteImport.update({
  id: '/game/$sessionId',
  path: '/game/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaveRoute = ApiLeaveRouteImport.update({
  id: '/api/leave',
  path: '/api/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsSessionIdRoute = ApiEventsSessionIdRouteImport.update({
  id: '/api/events/$sessionId',
  path: '/api/events/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCleanupRoute = ApiCronCleanupRouteImport.update({
  id: '/api/cron/cleanup',
  path: '/api/cron/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/leave': typeof ApiLeaveRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/api/events/$sessionId': typeof ApiEventsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/leave': typeof ApiLeaveRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/api/events/$sessionId': typeof ApiEventsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/leave': typeof ApiLeaveRoute
  '/game/$sessionId': typeof GameSessionIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/cron/cleanup': typeof ApiCronCleanupRoute
  '/api/events/$sessionId': typeof ApiEventsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/api/leave'
    | '/game/$sessionId'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/cron/cleanup'
    | '/api/events/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/api/leave'
    | '/game/$sessionId'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/cron/cleanup'
    | '/api/events/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/api/leave'
    | '/game/$sessionId'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/cron/cleanup'
    | '/api/events/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ApiLeaveRoute: typeof ApiLeaveRoute
  GameSessionIdRoute: typeof GameSessionIdRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiCronCleanupRoute: typeof ApiCronCleanupRoute
  ApiEventsSessionIdRoute: typeof ApiEventsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$sessionId': {
      id: '/game/$sessionId'
      path: '/game/$sessionId'
      fullPath: '/game/$sessionId'
      preLoaderRoute: typeof GameSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leave': {
      id: '/api/leave'
      path: '/api/leave'
      fullPath: '/api/leave'
      preLoaderRoute: typeof ApiLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$sessionId': {
      id: '/api/events/$sessionId'
      path: '/api/events/$sessionId'
      fullPath: '/api/events/$sessionId'
      preLoaderRoute: typeof ApiEventsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cleanup': {
      id: '/api/cron/cleanup'
      path: '/api/cron/cleanup'
      fullPath: '/api/cron/cleanup'
      preLoaderRoute: typeof ApiCronCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ApiLeaveRoute: ApiLeaveRoute,
  GameSessionIdRoute: GameSessionIdRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiCronCleanupRoute: ApiCronCleanupRoute,
  ApiEventsSessionIdRoute: ApiEventsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
